language: clojure
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
env:
  - LEIN_PROFILE=c08
  - LEIN_PROFILE=c09
  - LEIN_PROFILE=c10
script:
  - lein with-profile ${LEIN_PROFILE} test
matrix:
  exclude:
  - jdk: openjdk7
    env: LEIN_PROFILE=c10
