language: clojure
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
script:
  - lein with-profile c07 test
  - lein with-profile c08 test
  - lein with-profile c09 test
  - lein with-profile c10 test
matrix:
  exclude:
  - jdk: openjdk7
    script: lein with-profile c10 test
  - jdk: oraclejdk7
    script: lein with-profile c10 test
